
// Expenses
export const LOAD_OVERVIEW = 'LOAD_OVERVIEW'
export const LOAD_OVERVIEW_SUCCESS = 'LOAD_OVERVIEW_SUCCESS'
export const LOAD_OVERVIEW_ERROR = 'LOAD_OVERVIEW_ERROR'

export const LOAD_EXPENSES = 'LOAD_EXPENSES'
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS'
export const LOAD_EXPENSES_ERROR = 'LOAD_EXPENSES_ERROR'

export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS'
export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR'


// Categories
export const FACEBOOK_LOGOUT = 'FACEBOOK_LOGOUT'
export const FACEBOOK_LOGOUT_SUCCESS = 'FACEBOOK_LOGOUT_SUCCESS'
export const FACEBOOK_LOGOUT_ERROR = 'FACEBOOK_LOGOUT_ERROR'


// Users
export const FACEBOOK_LOGOUT = 'FACEBOOK_LOGOUT'
export const FACEBOOK_LOGOUT_SUCCESS = 'FACEBOOK_LOGOUT_SUCCESS'
export const FACEBOOK_LOGOUT_ERROR = 'FACEBOOK_LOGOUT_ERROR'
